global:
  appName: db
  image:
    repository: postgres
    tag: "15-alpine"
  postgres:
    user: postgres
    password: postgres

replicaCount: 1

service:
  type: ClusterIP
  port: 5432
  targetPort: 5432

persistence:
  enabled: true
  size: 1Gi
  storageClass: ""
