apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{ include "redis.labels" . | nindent 4 }}
  name: {{ include "redis.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "redis.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          name: redis
          ports:
            - containerPort: {{ .Values.service.port }}
              name: redis
          volumeMounts:
            - mountPath: /data
              name: redis-data
      volumes:
        - name: redis-data
          emptyDir: {}
