apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{ include "vote.labels" . | nindent 4 }}
  name: {{ include "vote.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "vote.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "vote.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          name: vote
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: vote
