apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{ include "worker.labels" . | nindent 4 }}
  name: {{ include "worker.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "worker.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          name: worker
