global:
  appName: redis
  image:
    repository: redis
    tag: "alpine"

replicaCount: 1

service:
  type: ClusterIP
  port: 6379
  targetPort: 6379

persistence:
  enabled: true
  size: 1Gi
  storageClass: ""
