apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{ include "postgres.labels" . | nindent 4 }}
  name: {{ include "postgres.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "postgres.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          name: postgres
          env:
            - name: POSTGRES_USER
              value: {{ .Values.global.postgres.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.global.postgres.password }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
      volumes:
        - name: db-data
          emptyDir: {}
