apiVersion: v1
kind: Service
metadata:
  labels:
    {{ include "postgres.labels" . | nindent 4 }}
  name: {{ include "postgres.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "db-service"
