name: Deploy Worker to AWS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy Worker (e.g., dev, staging, prod)'
        required: true
        type: string
        default: 'dev'

jobs:
  deploy:
    name: Deploy Worker to AWS
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Helm charts
        uses: actions/download-artifact@v3
        with:
          name: helm-charts

      - name: Pull Docker image
        run: |
          docker pull ghcr.io/${{ github.repository }}/ci-cd-image:latest

      - name: Run deployment
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace ghcr.io/${{ github.repository }}/ci-cd-image:latest bash -c "
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set default.region ${{ secrets.AWS_REGION }}
            helm upgrade --install my-worker ./my-worker-chart-*.tgz --namespace default --create-namespace
          "

      - name: Notify deployment
        run: echo "Worker deployment to ${{ github.event.inputs.environment }} completed."
