name: Build and Push Pre-Release Docker Image

on:
  push:
    branches:
      - 'feature/*'

jobs:
  build:
    name: Build Docker Image for Pre-Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker buildx build --tag my-app:${{ github.sha }} --tag my-app:pre-release-${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push my-app:${{ github.sha }}
          docker push my-app:pre-release-${{ github.sha }}

      - name: Output image details
        run: |
          echo "Docker image built and pushed: my-app:${{ github.sha }}"
          echo "Docker image pre-release tag: my-app:pre-release-${{ github.sha }}"
