name: Lint Helm Charts and YAML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Helm Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          helm-version: 'v3.9.4'

      - name: Lint Helm charts
        run: |
          echo "Linting Redis chart"
          helm lint charts/redis || exit 1
          echo "Linting Vote chart"
          helm lint charts/vote || exit 1
          echo "Linting Result chart"
          helm lint charts/result || exit 1
          echo "Linting Worker chart"
          helm lint charts/worker || exit 1
          echo "Linting Database chart"
          helm lint charts/database || exit 1

